name: build_package_LUNAR

on:
  push:
    branches:
      - "2.6-evo"
      - "dev-release"
      - "release"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: docker://ubuntu:lunar
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - name: Setup Old-Releases Repositories
        run: |
          sed -i 's|http://archive.ubuntu.com/ubuntu|http://old-releases.ubuntu.com/ubuntu|g' /etc/apt/sources.list
          sed -i 's|http://security.ubuntu.com/ubuntu|http://old-releases.ubuntu.com/ubuntu|g' /etc/apt/sources.list
          apt update

      - name: Test
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          apt install -y git sudo
          sudo apt install libpoco-dev -y

      - name: Clone OpenHD
        run: |
          git clone -b ${{ github.ref_name }} https://github.com/OpenHD/OpenHD --recursive
          cd OpenHD  

      - name: Install Dependencies
        run: |
          ls
          cd OpenHD
          apt install -y python3-pip
          pip install cloudsmith-api --break-system-packages
          pip install cloudsmith-cli --break-system-packages
          ./install_build_dep.sh ubuntu-x86

      - name: Build with make
        run: |
          cd OpenHD
          ./package.sh standard x86_64 ubuntu lunar

      - name: Upload to Github
        uses: 'actions/upload-artifact@v4'
        with:
          name: "OpenHD"
          path: |
            OpenHD/*.deb
            *.log
          if-no-files-found: error

      - name: Push
        if: github.ref_name == 'release' || github.ref_name == 'dev-release'
        run: |
          ls -a
          cloudsmith push deb  -k ${{ secrets.CLOUDSMITH_API_KEY }} openhd/${{ github.ref_name }}/ubuntu/lunar OpenHD/*.deb
